class ContextDb:
    def __new__(self, database_id: str, continuation_key: bytes) -> ContextDb: ...
    def observe_json(self, request_json: str) -> str: ...
    def recall_json(self, request_json: str) -> str: ...
    def explain_recall_json(self, request_json: str) -> str: ...
    def export_archive_json(self, request_json: str) -> str: ...
    def import_archive_json(self, request_json: str) -> str: ...
    def verify_json(self, request_json: str) -> str: ...
