use contextdb_storage::Keyspace;

use crate::Result;

#[derive(Clone, Debug)]
pub(crate) struct Keyspaces {
    pub meta: Keyspace,
    pub id_external: Keyspace,
    pub id_dense: Keyspace,
    pub object_kind: Keyspace,
    pub workspace_identity: Keyspace,
    pub space_identity: Keyspace,
    pub subject_identity: Keyspace,
    pub administrative_policy: Keyspace,
    pub subject_by_workspace: Keyspace,
    pub subject_by_space: Keyspace,
    pub space_by_workspace: Keyspace,
    pub space_by_owner: Keyspace,
    pub node_identity: Keyspace,
    pub node_revision: Keyspace,
    pub node_head: Keyspace,
    pub claim_identity: Keyspace,
    pub claim_revision: Keyspace,
    pub claim_head: Keyspace,
    pub edge_identity: Keyspace,
    pub edge_revision: Keyspace,
    pub edge_head: Keyspace,
    pub conflict_identity: Keyspace,
    pub conflict_revision: Keyspace,
    pub conflict_head: Keyspace,
    pub policy: Keyspace,
    pub policy_history: Keyspace,
    pub by_workspace: Keyspace,
    pub by_subject: Keyspace,
    pub by_scope: Keyspace,
    pub by_owner: Keyspace,
    pub by_space: Keyspace,
    pub by_audience: Keyspace,
    pub by_purpose: Keyspace,
    pub edge_out_delta: Keyspace,
    pub edge_in_delta: Keyspace,
    pub segment: Keyspace,
    pub segment_v2: Keyspace,
    pub manifest_history: Keyspace,
    pub artifact: Keyspace,
    pub publication: Keyspace,
    pub semantic_snapshot: Keyspace,
}

impl Keyspaces {
    pub fn new() -> Result<Self> {
        Ok(Self {
            meta: Keyspace::new("graph_meta_v1")?,
            id_external: Keyspace::new("graph_id_external_v1")?,
            id_dense: Keyspace::new("graph_id_dense_v1")?,
            object_kind: Keyspace::new("graph_object_kind_v1")?,
            workspace_identity: Keyspace::new("graph_workspace_identity_v1")?,
            space_identity: Keyspace::new("graph_space_identity_v1")?,
            subject_identity: Keyspace::new("graph_subject_identity_v1")?,
            administrative_policy: Keyspace::new("graph_administrative_policy_v1")?,
            subject_by_workspace: Keyspace::new("graph_subject_by_workspace_v1")?,
            subject_by_space: Keyspace::new("graph_subject_by_space_v1")?,
            space_by_workspace: Keyspace::new("graph_space_by_workspace_v1")?,
            space_by_owner: Keyspace::new("graph_space_by_owner_v1")?,
            node_identity: Keyspace::new("graph_node_identity_v1")?,
            node_revision: Keyspace::new("graph_node_revision_v1")?,
            node_head: Keyspace::new("graph_node_head_v1")?,
            claim_identity: Keyspace::new("graph_claim_identity_v1")?,
            claim_revision: Keyspace::new("graph_claim_revision_v1")?,
            claim_head: Keyspace::new("graph_claim_head_v1")?,
            edge_identity: Keyspace::new("graph_edge_identity_v1")?,
            edge_revision: Keyspace::new("graph_edge_revision_v1")?,
            edge_head: Keyspace::new("graph_edge_head_v1")?,
            conflict_identity: Keyspace::new("graph_conflict_identity_v1")?,
            conflict_revision: Keyspace::new("graph_conflict_revision_v1")?,
            conflict_head: Keyspace::new("graph_conflict_head_v1")?,
            policy: Keyspace::new("graph_policy_v1")?,
            policy_history: Keyspace::new("graph_policy_history_v1")?,
            by_workspace: Keyspace::new("graph_by_workspace_v1")?,
            by_subject: Keyspace::new("graph_by_subject_v1")?,
            by_scope: Keyspace::new("graph_by_scope_v1")?,
            by_owner: Keyspace::new("graph_by_owner_v1")?,
            by_space: Keyspace::new("graph_by_space_v1")?,
            by_audience: Keyspace::new("graph_by_audience_v1")?,
            by_purpose: Keyspace::new("graph_by_purpose_v1")?,
            edge_out_delta: Keyspace::new("graph_edge_out_delta_v1")?,
            edge_in_delta: Keyspace::new("graph_edge_in_delta_v1")?,
            segment: Keyspace::new("graph_segment_v1")?,
            segment_v2: Keyspace::new("graph_segment_v2")?,
            manifest_history: Keyspace::new("graph_manifest_history_v1")?,
            artifact: Keyspace::new("graph_artifact_v1")?,
            publication: Keyspace::new("graph_publication_v1")?,
            semantic_snapshot: Keyspace::new("graph_semantic_snapshot_v1")?,
        })
    }
}
